protected/models/Questions.php
<?php

/**
 * This is the model class for table "questions".
 *
 * The followings are the available columns in table 'questions':
 * @property integer $QuestionsId
 * @property integer $userId
 * @property integer $subId
 * @property string $Text
 * @property string $date
 * @property string $Description
 *
 * The followings are the available model relations:
 * @property Answers[] $answers
 * @property Users[] $users
 * @property Users[] $users1
 * @property Users $user
 * @property Subject $sub
 */
class Questions extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'questions';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('userId, subId', 'required'),
			array('userId, subId', 'numerical', 'integerOnly'=>true),
			array('date', 'length', 'max'=>45),
			array('Text, Description', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('QuestionsId, userId, subId, Text, date, Description', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'answers' => array(self::HAS_MANY, 'Answers', 'QuestionId'),
			'users' => array(self::MANY_MANY, 'Users', 'favorite(QuestionId, userid)'),
			'users1' => array(self::MANY_MANY, 'Users', 'follower(questionId, userid)'),
			'user' => array(self::BELONGS_TO, 'Users', 'userId'),
			'sub' => array(self::BELONGS_TO, 'Subject', 'subId'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'QuestionsId' => 'Questions',
			'userId' => 'User',
			'subId' => 'Sub',
			'Text' => 'Text',
			'date' => 'Date',
			'Description' => 'Description',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('QuestionsId',$this->QuestionsId);
		$criteria->compare('userId',$this->userId);
		$criteria->compare('subId',$this->subId);
		$criteria->compare('Text',$this->Text,true);
		$criteria->compare('date',$this->date,true);
		$criteria->compare('Description',$this->Description,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Questions the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/QuestionsController.php
<?php

class QuestionsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

private $_sub = null; 
	/**
	* Protected method to load the associated Project model class
	* @param integer projectId the primary identifier of the associated Project
	* @return object the Project data model based on the primary key 
	*/
	
	protected function loadSub($subId) {
	//if the project property is null, create it based on input id
		if($this->_sub===null)
		{
			$this->_sub=Subject::model()->findByPk($subId);
			if($this->_sub===null)
			{
				throw new CHttpException(404,'The requested Subject does not exist.'); 
			}
		}
		return $this->_sub; 
	} 
	/**
	* In-class defined filter method, configured for use in the above filters() 
	* method. It is called before the actionCreate() action method is run in 
	* order to ensure a proper project context
	*/
	public function filterSubContext($filterChain)
	{ 
	//set the project identifier based on GET input request variables 
		if(isset($_GET['sid']))
			$this->loadSub($_GET['sid']); 
		else
			throw new CHttpException(403,'Must specify a Subject before performing this action.');
	//complete the running of other filters and execute the requested action
		$filterChain->run();
	}
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
			'subContext + index create',
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','UpdateAnswers'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete','update'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$answerDataProvider=new CActiveDataProvider('Answers'
			, array(
				'criteria'=>array(
					'condition'=>'QuestionId=:QuestionsId',
					'params'=>array(':QuestionsId'=>$this->loadModel($id)->QuestionsId),
					),
				)
			);
 		$this->render('view',array(
			'model'=>$this->loadModel($id),
			'answerDataProvider'=>$answerDataProvider,
		));

		// $this->render('view',array(
		// 	'model'=>$this->loadModel($id),
		// ));
	}
	public function pushNotification($subjectId,$userid,$questionId)
	{
        $doctors = Yii::app()->db->createCommand("SELECT * FROM doctors WHERE SubId=$subjectId")->queryAll();
        $student = Yii::app()->db->createCommand("SELECT * FROM users WHERE userid=$userid")->queryAll();
        $subject = Yii::app()->db->createCommand("SELECT * FROM subject WHERE SubjectId=$subjectId")->queryAll();
        $size=count($doctors);
        $studentsSize=count($student);
        $subjectSize=count($subject);
        if($studentsSize>0 && $subjectSize>0){
            for($i=0;$i<$size;$i++){
                $doctor=$doctors[$i];
                $doctorUserID=$doctor['userId'];
                $text="New question at ".$subject[0]['Name'] . " asked by ".$student[0]['Fname'].' '.$student[0]['Lname'];
                Yii::app()->db->createCommand("INSERT INTO notification (userid,text,questionId , seen , type) VALUES ($doctorUserID,'$text', $questionId,'0','ask');")->execute();
            }
        }
    }
	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Questions;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
		if(isset($_POST['Questions']))
		{
			$model->attributes = $_POST['Questions'];
			$userId = Yii::app()->user->getId();;
			$subId = $this->_sub->SubjectId;
			$Text = $model->Text;
			$Description = $model->Description;
			$model->attributes=$_POST['Questions'];
			$date=getdate();
            $date=$date[0];
			Yii::app()->db->createCommand("INSERT INTO questions (userId,subId,Text,date,Description) VALUES($userId,$subId,'$Text','$date','$Description');")->execute();
			$lasId = Yii::app()->db->lastInsertID;
			$this->pushNotification($subId , $userId , $lasId);
			Yii::app()->db->createCommand("INSERT INTO follower (questionId , userid) values($lasId ,  $userId);")->execute();
			
			$this->redirect(array('view','id'=>$lasId));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}
	
	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Questions']))
		{
			$model->attributes=$_POST['Questions'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->QuestionsId));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Questions');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Questions('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Questions']))
			$model->attributes=$_GET['Questions'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Questions the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Questions::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Questions $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='questions-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

	public function actionUpdateAnswers($id)
        {           
		$answerDataProvider=new CActiveDataProvider('Answers'
			, array(
				'criteria'=>array(
					'condition'=>'QuestionId=:QuestionsId',
					'params'=>array(':QuestionsId'=>$this->loadModel($id)->QuestionsId),
					),
				)
			);
 		$this->renderPartial('renderAnswers',array(
			'answerDataProvider'=>$answerDataProvider,
		));
        }
        public function actionSearch($query){
            
        }
        static public function getName($id){
            $question = Yii::app()->db->createCommand("SELECT * FROM questions WHERE QuestionsId=$id")->queryAll();
            if(count($question)==0) return "";
            $userid=$question[0]['userId'];
            $user = Yii::app()->db->createCommand("SELECT * FROM users WHERE userid=$userid")->queryAll();
            if(count($user)==0) return "";
            return $user[0]['Fname'].' '.$user[0]['Lname'];
        }

}
?>

protected/views/questions/_answerform.php
<?php
/* @var $this AnswersController */
/* @var $model Answers */
/* @var $form CActiveForm */
?>

<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'answers-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>true,
        'htmlOptions'=>array(
                               'onsubmit'=>"return false;",/* Disable normal form submit */
                               'onkeypress'=>" if(event.keyCode == 13){ send(); } " /* Do ajax call when user presses enter key */
                             ),
)); ?>


	<?php echo $form->errorSummary($model); ?>

	<!-- <div class="row">
		<?php echo $form->labelEx($model,'QuestionId'); ?>
		<?php echo $form->textField($model,'QuestionId'); ?>
		<?php echo $form->error($model,'QuestionId'); ?>
	</div> -->

        <div id="hongkiat-form" >	
<div id="wrapping" class="clearfix">  
    <section id="aligned">  
        <textarea name="Answers[Text]" id="message" placeholder="Answer the Question" tabindex="5" class="txtblock"></textarea>  
    </section> 
    </div>
            </div>
	<div class="row">
		<?php echo $form->error($model,'Text'); ?>
	</div>

<!-- 	<div class="row">
		<?php echo $form->labelEx($model,'Date'); ?>
		<?php echo $form->textField($model,'Date',array('size'=>45,'maxlength'=>45)); ?>
		<?php echo $form->error($model,'Date'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'approved'); ?>
		<?php echo $form->textField($model,'approved',array('size'=>45,'maxlength'=>45)); ?>
		<?php echo $form->error($model,'approved'); ?>
	</div> -->
<section id="buttons" align=right">  
    <input onclick="send();" class="submitbtn"  name="yt0" type="button" value="answer" id="submitbtn" />
</section><br><br>
<script type="text/javascript">
 
function send()
 {
 
   var data=$("#answers-form").serialize();
 
  $.ajax({
   type: 'POST',
    url: '<?php echo Yii::app()->createAbsoluteUrl("answers/create?qid=".$model->QuestionId); ?>',
   data:data,
success:function(data){
    $( "#answersdata" ).load( "<?php echo Yii::app()->createAbsoluteUrl("questions/UpdateAnswers?id=".$model->QuestionId); ?>" );
              },
   error: function(data) { // if error occured
         alert("Error occured.please try again");
    },
 
  dataType:'html'
  });
 
}
 
</script>
<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/questions/_form.php
<?php
/* @var $this QuestionsController */
/* @var $model Questions */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'questions-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<!-- <div class="row">
		<?php echo $form->labelEx($model,'userId'); ?>
		<?php echo $form->textField($model,'userId'); ?>
		<?php echo $form->error($model,'userId'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'subId'); ?>
		<?php echo $form->textField($model,'subId'); ?>
		<?php echo $form->error($model,'subId'); ?>
	</div> -->

	<div class="row">
		<?php echo $form->labelEx($model,'Question'); ?>
		<?php echo $form->textArea($model,'Text',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'Text'); ?>
	</div>

	<div class="row">
		<?php $date=getdate();
                echo $form->hiddenField($model,'date',array('value'=>$date[0],'size'=>45,'maxlength'=>45)); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'Description'); ?>
		<?php echo $form->textArea($model,'Description',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'Description'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/questions/_search.php
<?php
/* @var $this QuestionsController */
/* @var $model Questions */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'QuestionsId'); ?>
		<?php echo $form->textField($model,'QuestionsId'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'userId'); ?>
		<?php echo $form->textField($model,'userId'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'subId'); ?>
		<?php echo $form->textField($model,'subId'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'Text'); ?>
		<?php echo $form->textArea($model,'Text',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'date'); ?>
		<?php echo $form->textField($model,'date',array('size'=>45,'maxlength'=>45)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'Description'); ?>
		<?php echo $form->textArea($model,'Description',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/questions/_view.php
<?php
/* @var $this QuestionsController */
/* @var $data Questions */
?>

<div class="view">

	<h3>
		<?php echo CHtml::link(CHtml::encode($data->Text), array('questions/view', 'id'=>$data->QuestionsId)); ?>
	</h3>

<!-- 	<b><?php echo CHtml::encode($data->getAttributeLabel('QuestionsId')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->QuestionsId), array('view', 'id'=>$data->QuestionsId)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('userId')); ?>:</b>
	<?php echo CHtml::encode($data->userId); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('subId')); ?>:</b>
	<?php echo CHtml::encode($data->subId); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Text')); ?>:</b>
	<?php echo CHtml::encode($data->Text); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('date')); ?>:</b>
	<?php echo CHtml::encode($data->date); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Description')); ?>:</b>
	<?php echo CHtml::encode($data->Description); ?>
	<br />
 -->

</div>

protected/views/questions/admin.php
<?php
/* @var $this QuestionsController */
/* @var $model Questions */

$this->breadcrumbs=array(
	'Questions'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Questions', 'url'=>array('index')),
	array('label'=>'Create Questions', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#questions-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Questions</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'questions-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'QuestionsId',
		'userId',
		'subId',
		'Text',
		'date',
		'Description',
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/questions/create.php
<?php
/* @var $this QuestionsController */
/* @var $model Questions */

$this->breadcrumbs=array(
	'Questions'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Questions', 'url'=>array('index')),
	array('label'=>'Manage Questions', 'url'=>array('admin')),
);
?>

<h1>Create Questions</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/questions/index.php
<?php
/* @var $this QuestionsController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Questions',
);

$this->menu=array(
	array('label'=>'Create Questions', 'url'=>array('create')),
	array('label'=>'Manage Questions', 'url'=>array('admin')),
);
?>

<h1>Questions</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/questions/renderAnswers.php
<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
$count=Yii::app()->db->createCommand("SELECT COUNT(Answerid) FROM answers where QuestionId='$QuestionsId'")->queryScalar();
$sql="SELECT * FROM answers where QuestionId='$QuestionsId' ORDER BY approved DESC";
$dataProvider=new CSqlDataProvider($sql,array(
        'keyField' => 'Answerid',
        'totalItemCount'=>$count,
        'pagination'=>array(
        'pageSize'=>10,
    )));


$this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'/answers/_view',
));
?>

protected/views/questions/update.php
<?php
/* @var $this QuestionsController */
/* @var $model Questions */

$this->breadcrumbs=array(
	'Questions'=>array('index'),
	$model->QuestionsId=>array('view','id'=>$model->QuestionsId),
	'Update',
);

$this->menu=array(
	array('label'=>'List Questions', 'url'=>array('index')),
	array('label'=>'Create Questions', 'url'=>array('create')),
	array('label'=>'View Questions', 'url'=>array('view', 'id'=>$model->QuestionsId)),
	array('label'=>'Manage Questions', 'url'=>array('admin')),
);
?>

<h1>Update Questions <?php echo $model->QuestionsId; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/questions/view.php
<script type="text/javascript">
    function likejsq(field_id ){
        var base_url = "<?php echo Yii::app()->baseUrl;?>/index.php/questionLike/likedislike";
        $.post( base_url, {field_id:field_id} ,
        function(data) {
            $("#displaytext_"+field_id).html(data.displaytext);
            $("#likedislikecount_"+field_id).html(data.count);
        },'json');
    }</script>



<script type="text/javascript">
    function followjsq(field_id ){
        var base_url = "<?php echo Yii::app()->baseUrl;?>/index.php/Follower/followunfollow";
        $.post( base_url, {field_id:field_id} ,
        function(data) { $("#displaytext2_"+field_id).html(data.displaytext2); },'json');
    }</script>


<script type="text/javascript">
    function favjsq(field_id ){
        var base_url = "<?php echo Yii::app()->baseUrl;?>/index.php/users/favorite";
        $.post( base_url, {field_id:field_id} ,
        function(data) { $("#displaytext3_"+field_id).html(data.displaytext3); },'json');
    }</script>
<?php
 $user_id  = Yii::app()->user->getId();
/* @var $this QuestionsController */
/* @var $model Questions */

$this->breadcrumbs=array(
	'Questions'=>array('index'),
	$model->QuestionsId,
);

$this->menu=array(
	array('label'=>'List Questions', 'url'=>array('index')),
	array('label'=>'Create Questions', 'url'=>array('create')),
	array('label'=>'Update Questions', 'url'=>array('update', 'id'=>$model->QuestionsId)),
	array('label'=>'Delete Questions', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->QuestionsId),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Questions', 'url'=>array('admin')),
	array('label'=>'Create Answer', 'url'=>array('answers/create', 'qid'=>$model->QuestionsId)),
);
    $QID=$model->QuestionsId;
    $this->widget('application.components.questionsAll', array(
   'question' => $model,
   'user_id' => $user_id,
   'QID' => $QID,
   'seemore'=>false,
    'questionUserName'=>$this->getName($QID),
));
?>

<br />
<article>
    <section>
        <?php 		
            $model2=new Answers;
        	$model2->QuestionId = $model->QuestionsId;
        	$model2->userId = Yii::app()->user->getId();
            $this->renderPartial('_answerform', array('model'=>$model2)); 
        ?>
        </section>
    </article>
<div id='answersdata'>
<?php
$this->renderPartial('renderAnswers', array('QuestionsId'=>$model2->QuestionId));
?>
</div>