protected/models/Departments.php
<?php

/**
 * This is the model class for table "departments".
 *
 * The followings are the available columns in table 'departments':
 * @property integer $DepartmentId
 * @property string $Name
 *
 * The followings are the available model relations:
 * @property Subject[] $subjects
 * @property Users[] $users
 */
class Departments extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'departments';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('Name', 'length', 'max'=>45),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('DepartmentId, Name', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'subjects' => array(self::HAS_MANY, 'Subject', 'DepId'),
			'users' => array(self::HAS_MANY, 'Users', 'DepId'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'DepartmentId' => 'Department',
			'Name' => 'Name',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('DepartmentId',$this->DepartmentId);
		$criteria->compare('Name',$this->Name,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Departments the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/DepartmentsController.php
<?php

class DepartmentsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';


	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
			);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
				),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array(''),
				'users'=>array('@'),
				),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete','update','create'),
				'users'=>array('@'),
				),
			array('deny',  // deny all users
				'users'=>array('*'),
				),
			);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView()
	{
        $id=Yii::app()->user->getState('DepId');
		$subjectDataProvider=new CActiveDataProvider('Subject' 
			, array(
				'criteria'=>array(
					'condition'=>'DepId=:DepartmentId',
					'params'=>array(':DepartmentId'=>$this->loadModel($id)->DepartmentId),
					'order'=>'year , Term',
					),
				)
			);
		$this->render('view',array(
			'model'=>$this->loadModel($id),
			'subjectDataProvider'=>$subjectDataProvider,
			));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Departments;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Departments']))
		{
			$model->attributes=$_POST['Departments'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->DepartmentId));
		}

		$this->render('create',array(
			'model'=>$model,
			));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Departments']))
		{
			$model->attributes=$_POST['Departments'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->DepartmentId));
		}

		$this->render('update',array(
			'model'=>$model,
			));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Departments');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
			));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Departments('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Departments']))
			$model->attributes=$_GET['Departments'];

		$this->render('admin',array(
			'model'=>$model,
			));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Departments the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Departments::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Departments $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='departments-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/SubjectController.php
<?php

class SubjectController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	* @var private property containing the associated Project model instance.
	*/
	private $_dept = null; 
	/**
	* Protected method to load the associated Project model class
	* @param integer projectId the primary identifier of the associated Project
	* @return object the Project data model based on the primary key 
	*/
	protected function loadDept($deptId) {
	//if the project property is null, create it based on input id
		if($this->_dept===null)
		{
			$this->_dept=Departments::model()->findByPk($deptId);
			if($this->_dept===null)
			{
				throw new CHttpException(404,'The requested Department does not exist.'); 
			}
		}
		return $this->_dept; 
	} 
	/**
	* In-class defined filter method, configured for use in the above filters() 
	* method. It is called before the actionCreate() action method is run in 
	* order to ensure a proper project context
	*/
	public function filterDeptContext($filterChain)
	{ 
	//set the project identifier based on GET input request variables 
		if(isset($_GET['did']))
			$this->loadDept($_GET['did']); 
		else
			throw new CHttpException(403,'Must specify a Department before performing this action.');
	//complete the running of other filters and execute the requested action
		$filterChain->run();
	}


	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
			'deptContext + index admin create', //check to ensure valid project context
			);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
				),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('favorites','Search','ViewUsersAdmin'),
				'users'=>array('@'),
				),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete','create','update'),
				'users'=>array('admin'),
				),
			array('deny',  // deny all users
				'users'=>array('*'),
				),
			);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionFavorites($id)
	{
		$this->render('favorites',array(
			'model'=>$this->loadModel($id),
		));
	}
	public function actionView($id)
	{
		$questionDataProvider=new CActiveDataProvider('Questions'
			, array(
				'criteria'=>array(
					'condition'=>'subId=:SubjectId',
					'params'=>array(':SubjectId'=>$this->loadModel($id)->SubjectId),
					),
				)
			);
                $subjectid=$id;
                $subjects=array();
                $subjects = Yii::app()->db->createCommand("SELECT * FROM questions WHERE subId=$subjectid")->queryAll();
		$this->render('view',array(
                        'subjectid'=>$subjectid,
                        'subjects'=>$subjects,
			'model'=>$this->loadModel($id),
			'questionDataProvider'=>$questionDataProvider,
			));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Subject;
		$model->DepId = $this->_dept->DepartmentId;
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Subject']))
		{
			$model->attributes=$_POST['Subject'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->SubjectId));
		}

		$this->render('create',array(
			'model'=>$model,
			));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Subject']))
		{
			$model->attributes=$_POST['Subject'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->SubjectId));
		}

		$this->render('update',array(
			'model'=>$model,
			));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Subject');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
			));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Subject('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Subject']))
			$model->attributes=$_GET['Subject'];

		$this->render('admin',array(
			'model'=>$model,
			));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Subject the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Subject::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Subject $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='subject-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
        static public function getName($id){
            $question = Yii::app()->db->createCommand("SELECT * FROM questions WHERE QuestionsId=$id")->queryAll();
            if(count($question)==0) return "";
            $userid=$question[0]['userId'];
            $user = Yii::app()->db->createCommand("SELECT * FROM users WHERE userid=$userid")->queryAll();
            if(count($user)==0) return "";
            return $user[0]['Fname'].' '.$user[0]['Lname'];
        }
        public function actionSearch($query){
                $subjectid=1;
                $subjects=array();
                $subjects = Yii::app()->db->createCommand("SELECT * FROM questions WHERE Text LIKE '%$query%' OR Description LIKE '%$query%'")->queryAll();
		$this->render('search',array('subjects'=>$subjects,));            
        }
        public function actionViewUsersAdmin($id){
            
 		$this->render('usersViewAdmin',array(
			'model'=>$this->loadModel($id),
		));           
        }
}

protected/views/departments/_form.php
<?php
/* @var $this DepartmentsController */
/* @var $model Departments */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'departments-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'Name'); ?>
		<?php echo $form->textField($model,'Name',array('size'=>45,'maxlength'=>45)); ?>
		<?php echo $form->error($model,'Name'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/departments/_search.php
<?php
/* @var $this DepartmentsController */
/* @var $model Departments */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'DepartmentId'); ?>
		<?php echo $form->textField($model,'DepartmentId'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'Name'); ?>
		<?php echo $form->textField($model,'Name',array('size'=>45,'maxlength'=>45)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/departments/_view.php
<?php
/* @var $this DepartmentsController */
/* @var $data Departments */
?>

<div class="view">

	
	<li><h2><?php echo CHtml::link(CHtml::encode($data->Name), array('view', 'id'=>$data->DepartmentId)); ?></h2></li>
	<br />

</div>

protected/views/departments/admin.php
<?php
/* @var $this DepartmentsController */
/* @var $model Departments */

$this->breadcrumbs=array(
	'Departments'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Departments', 'url'=>array('index')),
	array('label'=>'Create Departments', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#departments-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Departments</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'departments-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'DepartmentId',
		'Name',
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/departments/create.php
<?php
/* @var $this DepartmentsController */
/* @var $model Departments */

$this->breadcrumbs=array(
	'Departments'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Departments', 'url'=>array('index')),
	array('label'=>'Manage Departments', 'url'=>array('admin')),
);
?>

<h1>Create Departments</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/departments/index.php
<?php
/* @var $this DepartmentsController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Departments',
);

$this->menu=array(
	array('label'=>'Create Departments', 'url'=>array('create')),
	array('label'=>'Manage Departments', 'url'=>array('admin')),
);
?>

<h1>Departments</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/departments/update.php
<?php
/* @var $this DepartmentsController */
/* @var $model Departments */

$this->breadcrumbs=array(
	'Departments'=>array('index'),
	$model->Name=>array('view','id'=>$model->DepartmentId),
	'Update',
);

$this->menu=array(
	array('label'=>'List Departments', 'url'=>array('index')),
	array('label'=>'Create Departments', 'url'=>array('create')),
	array('label'=>'View Departments', 'url'=>array('view', 'id'=>$model->DepartmentId)),
	array('label'=>'Manage Departments', 'url'=>array('admin')),
);
?>

<h1>Update Departments <?php echo $model->DepartmentId; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/departments/view.php
<?php
/* @var $this DepartmentsController */
/* @var $model Departments */

$this->breadcrumbs=array(
	'Departments'=>array('index'),
	$model->Name,
);

$this->pageTitle = $model->Name;
$userid=yii::app()->user->getId();
$current_user=  Users::model()->findByPk($userid);
if($current_user->type=='superadmin'){
    $this->menu=array(
            array('label'=>'List Departments', 'url'=>array('index')),
            array('label'=>'Create Departments', 'url'=>array('create')),
            array('label'=>'Update Departments', 'url'=>array('update', 'id'=>$model->DepartmentId)),
            array('label'=>'Delete Departments', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->DepartmentId),'confirm'=>'Are you sure you want to delete this item?')),
            array('label'=>'Manage Departments', 'url'=>array('admin')),
            array('label'=>'Create Subejct', 'url'=>array('subject/create', 'did'=>$model->DepartmentId)),
    );
}
?>
<article>
    <section>
        <br />
        <h1>Department Sujects</h1>
        <?php $this->widget('zii.widgets.CListView', array(
        	'dataProvider'=>$subjectDataProvider,
        	'itemView'=>'/subject/_view',
        )); ?>
    </section>
</article>